code:
    build: code
    volumes:
        - ./cidemo:/var/www/symfony
    tty: true
php:
    build: php
    ports:
        - 9000:9000
    volumes_from:
        - code
nginx:
    build: nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - code
    volumes:
        - /var/log/nginx:/var/log/nginx